### PR TITLE
blobltoolkit i/o subworkflow

### PR DESCRIPTION
**Pull request by alxndrdiaz**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/blobtoolkit/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/blobtoolkit _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

Issue: [ i/o automate input subworkflow #26](https://github.com/sanger-tol/blobtoolkit/issues/26)

### CODE REVIEW

**Comment by alxndrdiaz** [comment]
For the 2 failing checks :
```
Run nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results
N E X T F L O W  ~  version 21.10.3
Launching `/home/runner/work/blobtoolkit/blobtoolkit/main.nf` [angry_leakey] - revision: ebef3e10d4
Cannot enable more than one container engine -- Choose either one of: docker, singularity
```
Uses Docker while conf/test.config (lines 24 to 27) is using Singularity: 

```
// Singularity settings - normally provided through `conf/sanger.config`
singularity.enabled    = true
singularity.autoMounts = true
singularity.runOptions = '--bind /lustre --bind /nfs'
```

**Comment by priyanka-surana** [comment]
Did your tests run successfully in the farm?

**Comment by alxndrdiaz** [comment]
> Did your tests run successfully in the farm?

No: 

```
nextflow run main.nf -profile test,singularity
```

Gives the following Nextflow error:

```
ERROR: Validation of pipeline parameters failed!
* Missing required parameter: --input
```

**Comment by muffato** [comment]
@alxndrdiaz: the last two commits (d3542727a06b2e40438846abf9bd499fd7692a89 and 4721f526212b06fc1be6897026dae7b2fa7d8a24) shouldn't be there. They're undoing some recent changes we've pushed to the automate_io (adding proper versioning in all Python and Shell scripts)

**Comment by alxndrdiaz** [comment]
> @alxndrdiaz: the last two commits ([d354272](https://github.com/sanger-tol/blobtoolkit/commit/d3542727a06b2e40438846abf9bd499fd7692a89) and [4721f52](https://github.com/sanger-tol/blobtoolkit/commit/4721f526212b06fc1be6897026dae7b2fa7d8a24)) shouldn't be there. They're undoing some recent changes we've pushed to the automate_io (adding proper versioning in all Python and Shell scripts)

I just merged those changes, but if there is anything that need to be modified just let me know.

**Comment by alxndrdiaz** [comment]
Using: 

`nextflow run main.nf -profile test,singularity`

Gives the following output: 

```
executor >  local (6)
[80/eef32d] process > NFCORE_BLOBTOOLKIT:BLOBTOOLKIT:INPUT_CHECK:INPUT_TOL (1)                       [100%] 1 of 1 ✔
[69/5684d5] process > NFCORE_BLOBTOOLKIT:BLOBTOOLKIT:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv) [100%] 1 of 1 ✔
[1c/a00e46] process > NFCORE_BLOBTOOLKIT:BLOBTOOLKIT:SAMTOOLS_VIEW (mMelMel3_T2)                     [100%] 4 of 4 ✔

-[nf-core/blobtoolkit] Pipeline completed successfully-
WARN: There's no process matching config selector: CUSTOM_DUMPSOFTWAREVERSIONS
WARN: There's no process matching config selector: FASTQC
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: blobtoolkit/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
```

**Comment by alxndrdiaz** [comment]
This PR is part of the Google Summer of Code 2022 project: [Conversion of the BlobToolKit pipeline to Nextflow](https://summerofcode.withgoogle.com/myprojects/details/v89lHomV), GitHub repository: https://github.com/sanger-tol/blobtoolkit

**Pull request merged**
