### PR TITLE
Optional alignment subworkflow

### LINKED ISSUE #79: Add optional read mapping subworkflow
### Description of feature
- Add read mapping flag
- Import all alignment subworkflows

### PR DESCRIPTION
**Pull request by priyanka-surana**
Closes #79 

This PR adds an optional alignment subworkflow. It replicates the one currently in BTK. It is not meant to be high quality alignments. Quick sub-optimal alignments are good enough for BTK and hence this approach with minimap is implemented. Please add suggestions for arguments to improve alignment with Minimap without introducing more extensive aligners like BWAmem.

I would especially like your input on `bin/samplesheet.py`, `subworkflows/local/coverage_stats.nf`, `subworkflows/local/minimap_alignment.nf` and `workflows/blobtoolkit.nf`

### CODE REVIEW

**Review by muffato — COMMENTED** [review]
1. You're missing `align = true` in `conf/test_raw.config`
2. I think it's confusing that the `input` channel in `subworkflows/local/coverage_stats.nf` has different shapes depending on a parameter. I would suggest that you move the `SAMTOOLS_VIEW` that creates the CSI index to `workflows/blobtoolkit.nf` (in the `else` of `if (params.align)`) so that `ch_aligned` is always the BAM + CSI
3. There might be a problem with `bin/samplesheet.py`: by allowing `*.bam` there might be a clash during `SAMTOOLS_VIEW` because the input and output files could be named the same ? Maybe the `else` I was referring to in my previous point could check the file extension. If a BAM, then samtools index. If a CRAM, then samtools view ?
4. You need to add `pacbio_clr` as an allowed datatype in `bin/samplesheet.py`

**Comment by priyanka-surana** [comment]
1. Added
2. Fixed in an alternative way. Removed index from minimap alignment subworkflow.
3. `SAMTOOLS_VIEW` would output BAM back without any changes and with index so should not be a problem but I have added the index step. 
4. Added

These tests ran on the farm without errors using `nf-core_2.8`
```
nextflow run . -profile test,singularity -ansi-log false
nextflow run . -profile test_raw,singularity -ansi-log false
bsub -R 'select[mem>4000] rusage[mem=4000] span[hosts=1]' -n 2 -M 4000 -J btk_test_full -o btk.%J.o -e btk.%J.e "nextflow run . -profile test_full,singularity,sanger -ansi-log false"
```

**Review by alxndrdiaz — APPROVED** [review]
In the [Snakemake version](https://github.com/blobtoolkit/blobtoolkit/blob/main/src/blobtoolkit-pipeline/src/blobtoolkit-snakefiles/rules/run_minimap2_align.smk) of the minimap2 alignment the input are reads in FASTQ format while in this case CRAM/BAM files are transformed to FASTA and aligned again using minimap2: What is the  advantage for an user in doing so instead of simply using the input alignment file? Only wanted to clarify why this is useful.

The following test worked as expected with Nextflow 22.10.1: 

```
nextflow run . -profile test_raw,singularity -ansi-log false
```

**Review by muffato — APPROVED** [review]

**Comment by priyanka-surana** [comment]
> In the [Snakemake version](https://github.com/blobtoolkit/blobtoolkit/blob/main/src/blobtoolkit-pipeline/src/blobtoolkit-snakefiles/rules/run_minimap2_align.smk) of the minimap2 alignment the input are reads in FASTQ format while in this case CRAM/BAM files are transformed to FASTA and aligned again using minimap2: What is the advantage for an user in doing so instead of simply using the input alignment file? Only wanted to clarify why this is useful.
> 
> The following test worked as expected with Nextflow 22.10.1:
> 
> ```
> nextflow run . -profile test_raw,singularity -ansi-log false
> ```

Unaligned files can also be in CRAM, BAM format. So if the user provides that and the align flag, now we can align it here and run the rest of the steps. Earlier, the user was required to provide aligned files. This is a step in making this pipeline independent. I can look at adding support for FASTQ as well, but after we sort out the config file.

**Pull request merged**
