### PR TITLE
Test ci

### PR DESCRIPTION
**Pull request by muffato**
The purpose of this pull-request is to reinstate the CI tests on GitHub. The main trick is to simply add some steps to the CI workflow to download the necessary databases (NCBI Taxonomy and BUSCO).

At the same time, I recreated the reduced BUSCO databases with a script that is now under `/lustre/scratch123/tol/resources/nextflow/busco`. The new databases have 10 genes (or less) that are known hit and 5 genes that have no hit. Like in https://github.com/sanger-tol/genomenote/pull/77 I change the metauk parameters to make BUSCO even faster.

Other changes:

- All the test data are now under `/lustre/scratch123/tol/resources/nextflow/test-data`, which is fully synchronised with the S3 server.
- I've changed the minimum version to 22.10, now tested on GitHub. No error so far !
- I'm using the new, recommended, GitHub Action to launch Tower.
- I've renamed our Tower integration scripts as per our new convention.
- All "pipeline_info" outputs are now under `pipeline_info/blobtoolkit`, as per our new convention.
- I had to add the `docker.io/` prefix to a few containers as the default now is `quay.io`. This is actually the result of getting the CI to work ! We had not spotted the error because we only use Singularity on the farm.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/blobtoolkit/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by alxndrdiaz — COMMENTED** [review]
LGTM. The only comment is that the blastn databases for running the small and full tests are about 70 MB in size, if these 
files are too large to be part of the repo  then the remote paths for them have to be updated accordingly in this branch and in the blastn branch.  Otherwise it can be merged since both databases are already saved in `assets` folder in the blastn branch.

**Comment by muffato** [comment]
> The only comment is that the blastn databases for running the small and full tests are about 70 MB in size, if these
> files are too large to be part of the repo then the remote paths for them have to be updated accordingly in this branch and in the blastn branch.

That's absolutely fine. I actually think the `.dmnd` files should be moved from `assets/` to remote paths as well. Even if they're small, it's not the sort of things that should really be kept in the code repository.

**Comment by priyanka-surana** [comment]
@muffato Any other changes to this PR. Otherwise I would like to merge this into #83 and run the tests.

**Comment by muffato** [comment]
@priyanka-surana I moved the `.dmnd` files to S3 and updated the test config. Ready to merge !

**Review by priyanka-surana — APPROVED** [review]
Merging into alignment. Any further changes needed will be done in release branch.

**Pull request merged**
