### PR TITLE
Increase CI test resource

### PR DESCRIPTION
**Pull request by gq1**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by gq1** [comment]
Tried both 14G and 10G memory, it took 11mins compared with previous run only 8 mins with 6G memory.

**Comment by gq1** [comment]
Drop to 3 cores, still 11 mins.

**Comment by gq1** [comment]
Clearly the original setting with 2 cores and 6G memory is the fastest run 8-9 mins.

**Comment by muffato** [comment]
Not useful, indeed

**Pull request closed without merging**
