### PR TITLE
v0.3 - Pipeline now validated on five real genomes

### PR DESCRIPTION
**Pull request by muffato**
I've now tested the pipeline on five real, complete, genomes (though all under 100 Mbp). This PR is to fix all the issues I've found along the way:

- Fixed the conditional runs of blastn
- Fixed the generation of the no-hit list
- Fixed the conversion of the unaligned input files to Fasta
- Fixed the documentation about preparing the NT database
- Fixed the detection of the NT database in the nf-core module
- The pipeline now supports samplesheets generated by the
  [nf-core/fetchngs](https://nf-co.re/fetchngs) pipeline by passing the
  `--fetchngs_samplesheet true` option.
- FastQ files can bypass the conversion to Fasta
- Fixed missing BUSCO results from the blobdir (only 1 BUSCO was loaded)
- Fixed the default category used to colour the blob plots

I want to release this as the version 0.3.
The following is still needed for the version 1.0:

- Validation on >100 Mbp genomes, possibly with some improved resource requests.
- Validation on the usage for non public assemblies.

which may require another 0.\* release.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
To run on the farm, use these arguments:
```
--taxdump /lustre/scratch123/tol/resources/taxonomy/latest/new_taxdump
--busco /lustre/scratch123/tol/resources/busco/latest
--blastp /lustre/scratch123/tol/resources/uniprot_reference_proteomes/latest/reference_proteomes.dmnd
--blastx /lustre/scratch123/tol/resources/uniprot_reference_proteomes/latest/reference_proteomes.dmnd
--blastn /lustre/scratch123/tol/teams/tolit/users/mm49/nextflow/btk/prod_test/new_nt/untar
```

(there isn't a central NT database with taxonomy information yet. It's still in progress)

**Comment by muffato** [comment]
Prettier error fixed, thanks to @BethYates

**Comment by BethYates** [comment]
The code looks good but the images aren't being published to the results directory

**Comment by muffato** [comment]
@BethYates 

1. The images are now published in their directory
2. Introduced an output directory named `blobtoolkit` and turned `BUSCO` to lower case.
3. Images as PNG by default, but SVG can be generated with the option `--image_format svg`
4. I had to pin the version of nf-core for the linting to pass

**Review by BethYates — APPROVED** [review]

**Pull request merged**
